BOW,TFIDF,ML algorithms

1. Preprocessing and cleaning
2. BOW and TF-IDF (sentences----> vectors)
3. Train test split
4. Trained our Models

but there is a mistake in the order of performing steps..which we will see in next notebook.

In [ ]:
import pandas as pd
df = pd.read_csv('/content/spam.csv',encoding = 'latin-1')

In [ ]:
df = df.rename(columns={'v1':'label','v2':'text'})

In [ ]:
df = df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1)

In [ ]:
df = df.dropna()

In [ ]:
df.isna().sum()

label    0
text     0
dtype: int64

In [ ]:
df

label                                               text
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
#covert label column to numerical variables
y = df['label'].map({'ham':1,'spam':0})

In [ ]:
y

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: label, Length: 5572, dtype: int64

In [ ]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
wordlemmatize=WordNetLemmatizer()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
corpus = []
for i in range (0,len(df)):

  review = re.sub('[^a-zA-Z]',' ',df['text'][i]) #it says that apart from a to z and A to Z,if you find any special character,replace with blank.
  review = review.lower()
  review = review.split()
  review = [wordlemmatize.lemmatize(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [ ]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

**create Bag of words**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
#for binary BOW enable binary=True
cv = CountVectorizer(max_features=2500,binary=True,ngram_range=(1,2))
X = cv.fit_transform(corpus).toarray() #independent features

In [ ]:
import numpy as np
np.set_printoptions(edgeitems=30,linewidth=100000,
                    formatter=dict(float=lambda x: "%.3g" % x))
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [ ]:
cv.vocabulary_

{'go': 816,
 'point': 1607,
 'crazy': 451,
 'available': 106,
 'bugis': 215,
 'great': 860,
 'world': 2442,
 'la': 1083,
 'cine': 335,
 'got': 851,
 'wat': 2350,
 'ok': 1466,
 'lar': 1096,
 'joking': 1050,
 'wif': 2405,
 'free': 746,
 'entry': 637,
 'wkly': 2428,
 'comp': 389,
 'win': 2410,
 'cup': 464,
 'final': 703,
 'tkts': 2141,
 'st': 1956,
 'may': 1272,
 'text': 2072,
 'receive': 1706,
 'question': 1664,
 'std': 1971,
 'txt': 2209,
 'rate': 1678,
 'apply': 72,
 'free entry': 751,
 'entry wkly': 639,
 'cup final': 465,
 'std txt': 1972,
 'txt rate': 2213,
 'rate apply': 1680,
 'dun': 592,
 'say': 1794,
 'early': 599,
 'already': 46,
 'nah': 1383,
 'think': 2102,
 'usf': 2282,
 'life': 1153,
 'around': 82,
 'though': 2113,
 'freemsg': 758,
 'hey': 920,
 'darling': 492,
 'week': 2375,
 'word': 2437,
 'back': 125,
 'like': 1159,
 'fun': 776,
 'still': 1974,
 'tb': 2051,
 'xxx': 2469,
 'send': 1827,
 'rcv': 1686,
 'like fun': 1161,
 'even': 647,
 'brother': 205,
 'speak': 1935,
 'trea

In [ ]:
#train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train,y_train)

In [ ]:
y_pred = spam_detect_model.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
accuracy = accuracy_score(y_test,y_pred)
confusion_m = confusion_matrix(y_test,y_pred)

In [ ]:
print(accuracy)

0.9856502242152466


In [ ]:
print(confusion_m)

[[152  14]
 [  2 947]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.92      0.95       166
           1       0.99      1.00      0.99       949

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



**create TF-IDF model**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv =TfidfVectorizer(max_features=2500,ngram_range=(1,2))
x = tv.fit_transform(corpus).toarray()


In [ ]:
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [ ]:
tv.vocabulary_

{'go': 799,
 'point': 1602,
 'crazy': 451,
 'available': 117,
 'bugis': 229,
 'great': 854,
 'world': 2437,
 'la': 1079,
 'cine': 345,
 'got': 838,
 'wat': 2341,
 'ok': 1467,
 'lar': 1090,
 'joking': 1046,
 'wif': 2398,
 'free': 727,
 'entry': 613,
 'wkly': 2421,
 'comp': 405,
 'win': 2403,
 'cup': 459,
 'final': 683,
 'st': 1961,
 'may': 1258,
 'text': 2082,
 'receive': 1696,
 'question': 1657,
 'std': 1976,
 'txt': 2199,
 'rate': 1670,
 'apply': 79,
 'free entry': 732,
 'entry wkly': 615,
 'std txt': 1977,
 'txt rate': 2206,
 'rate apply': 1671,
 'dun': 567,
 'say': 1790,
 'early': 577,
 'already': 50,
 'nah': 1382,
 'think': 2102,
 'usf': 2275,
 'life': 1136,
 'around': 92,
 'though': 2110,
 'freemsg': 739,
 'hey': 918,
 'darling': 477,
 'week': 2367,
 'word': 2430,
 'back': 136,
 'like': 1141,
 'fun': 758,
 'still': 1979,
 'tb': 2056,
 'xxx': 2467,
 'send': 1824,
 'rcv': 1677,
 'even': 623,
 'brother': 221,
 'speak': 1943,
 'treat': 2171,
 'per': 1535,
 'request': 1732,
 'melle': 1

In [ ]:
#train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train,y_train)

In [ ]:
#prediction
y_pred = spam_tfidf_model.predict(X_test)

In [ ]:
score = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)

In [ ]:
print(score)

0.9695067264573991


In [ ]:
print(cm)

[[133  33]
 [  1 948]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.80      0.89       166
           1       0.97      1.00      0.98       949

    accuracy                           0.97      1115
   macro avg       0.98      0.90      0.93      1115
weighted avg       0.97      0.97      0.97      1115

